name: guardian-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - requests
  - feedparser
  - pip
  - pyaudio
  - pip:
      - fastapi
      - uvicorn
      - pydantic
      - google-genai
      - yfinance
      - python-dotenv
